name = "SkyCoords"
uuid = "fc659fc5-75a3-5475-a2ea-3da92c065361"
authors = "Kyle Barbary, Mos√© Giordano, and contributors"
version = "1.5.3"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
AccessorsExt = "Accessors"
MakieExt = "Makie"
NearestNeighborsExt = "NearestNeighbors"
UnitfulExt = "Unitful"

[compat]
Accessors = "0.1"
ConstructionBase = "1"
Makie = "0.21, 0.22, 0.23, 0.24"
NearestNeighbors = "0.4.9"
Rotations = "1"
StaticArrays = "0.8, 0.9, 1"
Unitful = "1.15"
julia = "1.6"

[extras]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
